image:
  - Visual Studio 2017

environment:
  MINICONDA: C:\Miniconda3
  PYTHON_VERSION: 3.6

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy pytest"
  - activate test-environment
  - pip install -U git+https://github.com/eScatter/cslib.git
  - pip install -U git+https://github.com/eScatter/pyelsepa.git
  - pip install -U .

build: off

test_script:
  - pytest test
